import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from './modules/Header'
import {Container, Row, Col, Table, Button, Form} from 'react-bootstrap'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shop 9 API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
          <Row>
            <Header/>
          </Row>
        </Container>
      
      <main className={styles.main}>
        <Container>
          <Row>
              <Col md="12">
                <h1 className={styles.title}>
                  Welcome to Shop 9 API
                </h1>
              </Col>
          </Row>
        </Container>
       

      </main>

    </div>
  )
}
